version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 8443:443
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB
